name: hierarchicalforecast
channels:
  - conda-forge
dependencies:
  - jupyterlab
  - numpy<1.24
  - numba
  - pandas
  - scikit-learn
  - proxsuite
  - matplotlib
  - tqdm
  - pip
  - pip:
    - nbdev
